name: iotivity-devel
version: 1.3.0
summary: IoTivity development package
description:
  This snap provides supports for developing IoTivity native apps
confinement: strict
grade: devel

apps:
  simpleserver:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      simpleserver

  simpleclient:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      simpleclient

  simpleclientserver:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      simpleclientserver

  directpairingclient:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      directpairingclient

  devicediscoveryserver:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      devicediscoveryserver

  devicediscoveryclient:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      devicediscoveryclient

  simpleserverHQ:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      simpleserverHQ

  simpleclientHQ:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      simpleclientHQ

  fridgeserver:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      fridgeserver

  fridgeclient:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      fridgeclient

  presenceserver:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      presenceserver

  presenceclient:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      presenceclient

  roomserver:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      roomserver

  roomclient:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      roomclient

  garageserver:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      garageserver

  garageclient:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      garageclient

  groupserver:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      groupserver

  groupclient:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      groupclient

  lightserver:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      lightserver

  threadingsample:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      threadingsample

  sampleResourceServer:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      sampleResourceServer

  separateResponseServer:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      separateResponseServer

  nestedAttributesServer:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      nestedAttributesServer

plugs:
  home:
    interface: home
  network:
    interface: network
  network-bind:
    interface: network-bind

slots:
  resource:
    interface: content
    read: [ usr/local/iotivity ]

parts:
  # Part builds from local source
  examples:
    plugin: scons
    source: examples
    after: [ iotivity ]

  # Part installs IoTivity
  iotivity:
    plugin: scons
    scons-options:
      - SECURED=1  # Build with DTLS (0|1)
      - octbstack
    source: https://gerrit.iotivity.org/gerrit/p/iotivity.git
    source-tag: 1.3.0
    prepare:
      # pull the tinycbor and mbedtls projects before building IoTivity
      git clone https://github.com/01org/tinycbor.git extlibs/tinycbor/tinycbor -b v0.4.1 |
      git clone https://github.com/ARMmbed/mbedtls.git extlibs/mbedtls/mbedtls -b mbedtls-2.4.0
    install: |
      # stage IoTivity header files
      install -d $SNAPCRAFT_PART_INSTALL/usr/local/iotivity
      cd resource
      rsync -aLm --include='*.h' --include='*.hpp' -f 'hide,! */' . $SNAPCRAFT_PART_INSTALL/usr/local/iotivity
      cd -
      # stage IoTivity libraries
      install -d $SNAPCRAFT_PART_INSTALL/usr/local/iotivity/lib
      install -t $SNAPCRAFT_PART_INSTALL/usr/local/iotivity/lib out/*/*/release/*.a
      install -t $SNAPCRAFT_PART_INSTALL/usr/local/iotivity/lib out/*/*/release/*.so
      # stage example code
      install -d $SNAPCRAFT_PART_INSTALL/usr/local/iotivity/examples/
      install -t $SNAPCRAFT_PART_INSTALL/usr/local/iotivity/examples resource/examples/*
      # stage service header files & examples
      install -d $SNAPCRAFT_PART_INSTALL/usr/local/iotivity/examples/resource-encapsulation
      cd service/resource-encapsulation/examples/linux
      rsync -aLm --include='*' -f 'hide,! */' . $SNAPCRAFT_PART_INSTALL/usr/local/iotivity/examples/resource-encapsulation
      cd -
      install -d $SNAPCRAFT_PART_INSTALL/usr/local/iotivity/service/resource-encapsulation
      install -t $SNAPCRAFT_PART_INSTALL/usr/local/iotivity/service/resource-encapsulation service/resource-encapsulation/include/*.h
    build-packages:
      # build prerequisties listed at
      # https://wiki.iotivity.org/build_iotivity_with_ubuntu_build_machine
      - libboost-dev
      - libboost-program-options-dev
      - libboost-thread-dev
      - uuid-dev
      - libexpat1-dev
      - libglib2.0-dev
      - libsqlite3-dev

