name: iotivity-devel
version: 1.2.1
summary: IoTivity development package
description:
  This snap provides supports for developing IoTivity native apps
confinement: strict
grade: devel

apps:
  simpleserver:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      simpleserver
    plugs: [ network-bind ]

  simpleclient:
    command: env \
      LD_LIBRARY_PATH=$SNAP/usr/local/iotivity/lib:$LD_LIBRARY_PATH \
      simpleclient
    plugs: [ network, network-bind ]

parts:
  # Part builds from local source
  examples:
    plugin: scons
    source: examples
    after: [ iotivity ]

  # Part installs IoTivity
  iotivity:
    plugin: scons
    scons-options:
      - SECURED=0  # Build with DTLS (0|1)
      - octbstack
    source: https://gerrit.iotivity.org/gerrit/p/iotivity.git
    source-tag: 1.2.1
    prepare:
      # pull the tinycbor code before building IoTivity
      git clone https://github.com/01org/tinycbor.git extlibs/tinycbor/tinycbor -b v0.4
    install: |
      # stage IoTivity header files
      install -d $SNAPCRAFT_PART_INSTALL/usr/local/iotivity
      cd resource
      rsync -am --include='*.h' --include='*.hpp' -f 'hide,! */' . $SNAPCRAFT_PART_INSTALL/usr/local/iotivity
      cd -
      # stage IoTivity libraries
      install -d $SNAPCRAFT_PART_INSTALL/usr/local/iotivity/lib
      install -t $SNAPCRAFT_PART_INSTALL/usr/local/iotivity/lib out/*/*/release/*.a
      install -t $SNAPCRAFT_PART_INSTALL/usr/local/iotivity/lib out/*/*/release/*.so
      # stage example code
      install -d $SNAPCRAFT_PART_INSTALL/usr/local/iotivity/examples/
      install -t $SNAPCRAFT_PART_INSTALL/usr/local/iotivity/examples resource/examples/*
    build-packages:
      # build prerequisties listed at
      # https://wiki.iotivity.org/build_iotivity_with_ubuntu_build_machine
      - libboost-dev
      - libboost-program-options-dev
      - libboost-thread-dev
      - uuid-dev
      - libexpat1-dev
      - libglib2.0-dev
      - libsqlite3-dev

