name: ocf-util
version: 1.3.0-1
summary: Utilities for testing OCF devices
description:
  This snap installs iotivity-node and iot-rest-api-server node modules
  for testing OCF implementations using Javascript.
confinement: strict
grade: devel

apps:
  start-iot-rest-api-server:
    command: env \
      LD_LIBRARY_PATH=$SNAP/lib/node_modules/iot-rest-api-server/node_modules/iotivity-node/iotivity-installed/lib:$LD_LIBRARY_PATH \
      NODE_PATH=$SNAP/lib/node_modules/iot-rest-api-server/node_modules \
      node $SNAP/lib/node_modules/iot-rest-api-server/index.js
    daemon: simple
    plugs: [ network-bind ]

  node:
    command: env \
      LD_LIBRARY_PATH=$SNAP/lib/node_modules/iot-rest-api-server/node_modules/iotivity-node/iotivity-installed/lib:$LD_LIBRARY_PATH \
      NODE_PATH=$SNAP/lib/node_modules:$SNAP/lib/node_modules/iot-rest-api-server/node_modules \
      node
    plugs: [ hardware-observe, home, network-bind ]

  hciconfig:
    command: bin/hciconfig
    plugs: [ bluez, bluetooth-control ]

  rfkill:
    command: usr/sbin/rfkill
    plugs: [ network-control ]

parts:
  # Part builds from local source
  local:
    plugin: nil
    source: .

  # Part installs iotivity, iotivity-node, iot-rest-api-server
  meta-iot-web:
    plugin: nodejs
    node-packages:
      # package.json: Update iotivity-node dependency and package version (#71)
      - 01org/iot-rest-api-server#b903fa79d81cc77e0b2424176c2c738f340d87f6
      # package.json: Bump version
      - otcshare/iotivity-node#ce496720c1d954335e07072d3a4c3f3862f71708
      # Useful node modules
      - mraa
      - noble
      - bleno
      - uuid
    filesets:
      exports:
        # ignore the following files during staging
        - -CHANGELOG.md
        - -LICENSE
        - -README.md
    organize:
      # replace the iotivity-node with the specified snapshot
      lib/node_modules/iotivity-node: lib/node_modules/iot-rest-api-server/node_modules/iotivity-node
    install:
      # drop the iotivity-node associated with the iot-rest-api-server before staging
      rm -rf $SNAPCRAFT_PART_INSTALL/lib/node_modules/iot-rest-api-server/node_modules/iotivity-node
    stage: [ $exports ]
    prime:  [ $exports ]

  # Part installs Ubuntu packages
  ubuntu:
    plugin: nil
    stage-packages:
      - rfkill          # provides /usr/sbin/rfkill
      - bluez           # provides /bin/hciconfig
