name: ocf-util
version: 1.2.0-2
summary: Utilities for testing OCF devices
description:
  This snap installs iotivity-node and iot-rest-api-server node modules
  for testing OCF implementations using Javascript.
confinement: strict
grade: devel

apps:
  start-iot-rest-api-server:
    command: env \
      LD_LIBRARY_PATH=$SNAP/lib/node_modules/iot-rest-api-server/node_modules/iotivity-node/iotivity-installed/lib:$LD_LIBRARY_PATH \
      NODE_PATH=$SNAP/lib/node_modules/iot-rest-api-server/node_modules \
      node $SNAP/lib/node_modules/iot-rest-api-server/index.js
    daemon: simple
    plugs: [ network-bind ]

  node:
    command: env \
      LD_LIBRARY_PATH=$SNAP/lib/node_modules/iot-rest-api-server/node_modules/iotivity-node/iotivity-installed/lib:$LD_LIBRARY_PATH \
      NODE_PATH=$SNAP/lib/node_modules:$SNAP/lib/node_modules/iot-rest-api-server/node_modules \
      node
    plugs: [ hardware-observe, home, network-bind ]

  hciconfig:
    command: bin/hciconfig
    plugs: [ bluez, bluetooth-control ]

  rfkill:
    command: usr/sbin/rfkill
    plugs: [ network-control ]

parts:
  # Part builds from local source
  local:
    plugin: nil
    source: .

  # Part installs iotivity, iotivity-node, iot-rest-api-server
  meta-iot-web:
    plugin: nodejs
    node-packages:
      # HEAD: package.json: package.json: publish new version (#53)
      - 01org/iot-rest-api-server#3979442c554d4aa0a73dd642f8448aeb78ee86ec
      # HEAD: AUTHORS.txt: Update authors
      - otcshare/iotivity-node#a4c1fd306851e854574f633f8298559bf510b7cd
      # Useful node modules
      - mraa
      - noble
      - bleno
    filesets:
      exports:
        # ignore the following files during staging
        - -CHANGELOG.md
        - -LICENSE
        - -README.md
    organize:
      # replace the iotivity-node with the specified snapshot
      lib/node_modules/iotivity-node: lib/node_modules/iot-rest-api-server/node_modules/iotivity-node
    install:
      # drop the iotivity-node associated with the iot-rest-api-server before staging
      rm -rf $SNAPCRAFT_PART_INSTALL/lib/node_modules/iot-rest-api-server/node_modules/iotivity-node
    stage: [ $exports ]
    snap:  [ $exports ]

  # Part installs Ubuntu packages
  ubuntu:
    plugin: nil
    stage-packages:
      - rfkill          # provides /usr/sbin/rfkill
      - bluez           # provides /bin/hciconfig
